name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install dependencies
      run: | 
        cd backend
        pnpm install

    - name: Run tests
      run: |
        cd backend
        pnpm test
