name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: |
        curl -fsSL https://get.pnpm.io/install.sh | sh
        export PATH="$HOME/.pnpm/bin:$PATH"

    - name: Install dependencies
      run: | 
        cd backend
        pnpm install

    - name: Run tests
      run: |
        cd backend
        pnpm test
